[versions]
agp = "8.5.0"
kotlin = "1.9.24"
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
junit = "4.13.2"
androidx-core-ktx = "1.13.1"
androidx-appcompat = "1.7.0"
material = "1.12.0"
androidx-test-ext = "1.1.5"
espresso-core = "3.5.1"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
