name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installa Android SDK (platform 34 e build-tools 34.0.0)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      # Installa Gradle "standalone" e genera il Gradle Wrapper nel repo
      - name: Install Gradle and generate wrapper
        run: |
          curl -sLo gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          echo "$GITHUB_WORKSPACE/gradle-8.7/bin" >> $GITHUB_PATH
          gradle -v
          gradle wrapper --gradle-version 8.7

      # Build debug APK
      - name: Build debug
        run: ./gradlew --no-daemon clean :app:assembleDebug

      # Carica l'APK come artifact scaricabile
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
